### ISSUE TITLE
Build error when using a recent gcc (all the things are not constexpr!)

### ISSUE THREAD

**Issue by kristerw** [lefticus/constexpr_all_the_things#1]
GCC 7 and earlier have a bug ([Bug 70167](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70167)) that it treats `T{}` in the same way as C99 compound literals. This was recently fixed, with the result that the trunk gcc now correctly gives errors for the construct `constexpr std::initializer_list<T> il{Ts...};` in `cx_json_parser.h` as `il` is not initialized by a constant expression (the standard specifies this initialization as involving pointers to a temporary object on the stack...).

**Comment by elbeno** [comment]
Thanks. I assume this refers to slide 76 since the code has not been this way in a while...

Fixed in https://github.com/lefticus/constexpr_all_the_things/commit/4714c97082220144ec7a34c4384b0c7ccb66afc5

**Comment by kristerw** [comment]
Hmm. I actually meant the source code...  But I see that I read the code too fast – it is only the GCC error message that talks about `constexpr`, not the source code. I'll dig some more into this, and will open a GCC bug...

**Comment by elbeno** [comment]
Thanks, and do let us know if there's anything wrong here. Good CppCast episode btw :)
