### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simonvpe** [lefticus/constexpr_all_the_things#2]
Hi Jason & Ben!

First I want to start of by saing "Great talk!" (as usual).
I'm prepping a talk for myself on a compile-time lisp interpreter, is it ok to use this project as a basis for my talk?

**Comment by lefticus** [comment]
Fine by me, we still need to add a license. @elbeno would you mind just adding whichever one you want?

**Comment by elbeno** [comment]
Added the MIT license.

**Comment by simonvpe** [comment]
Cool thx! I'll keep you posted whenever the talk is online - I will try to steal another slot on the combined London + Stockholm C++ meetup :D

**Comment by lefticus** [comment]
Yeah I'm pretty interested to see what you pull off for compile time lisp. could be really interesting.
